server:
  port: 8081

spring:
  application:
    name: dubboDemo

dubbo:
  scan:
    base-packages: com.ymj.service
  protocol:
    name: dubbo
    port: 20800
    host: localhost
  registry:
    address: zookeeper://192.168.195.132:2181
